### ISSUE TITLE
CSS 파일 관리에 대한 새로운 제안

### ISSUE THREAD

**Issue by copiCat0** [likelion-LAB12-VainillaProject/market-karly#27]
![image](https://user-images.githubusercontent.com/80018207/216215456-5e7b73a8-8e1e-4a08-8724-37b1a08aafeb.png)

제안이지만 당장 도입해야 합니다. "누군가"의 깃 레포에서 발견했고, 사진은 style.css의 내용 입니다. 일단 제가 해두겠습니다.

**Comment by copiCat0** [comment]
feedback 주시면 감사하겠습니다~! 👍

**Comment by HYBEN09** [comment]
오 나눠서 하면 좋겠네요!

**Comment by CALKO9611** [comment]
좋은 의견입니다!
이렇게 하면 merge 했을 시 편할 것 같습니다!
